# TODO
# this is project-specific

refgenomes:
  hg38:
    any: GRCh38_HGSVC2_noalt.fasta
  t2tv2:
    male: chm13v2.0.fasta
    male-hap: chm13v2.0.male-hap.fasta
    female: chm13v2.0_maskedY.fasta
    female-hap: chm13v2.0.female-hap.fasta
    any: chm13v2.0.fasta

complete_reference: t2tv2

sex_chromosomes:
  male:
    - chrY
  female:
    - chrX

# If set to True, enforce to use
# the annotated sample sex for all
# sex-specific assembly units.
# If set to False, infer on the basis
# of the contig-to-reference alignments
force_annotated_sample_sex: False

gene_models:
  gencodeV44:
    male: gencode.v44.pc_transcripts.122Y.fa.gz
    female: gencode.v44.pc_transcripts.122X.fa.gz
    any: gencode.v44.pc_transcripts.122XY.fa.gz
